# config/services.yaml
parameters:

services:

    _defaults:
        autowire: true      
        autoconfigure: true 
        bind:
            App\Persistence\PersistenceInterface: '@App\Persistence\SqlPersistence'
  
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\Service\JSONBackupDatabase:
        arguments:
            $projectDir: '%kernel.project_dir%'